insert into students (code, names, email, password, semester) values
('220034001', 'Yorth H. Ortegon', 'yorth21@gmail.com', 12);

insert into student_curricula (student_id, curriculum_id) values
((select id from students where code = '220034001'), (select id from curricula where version = '2018'));

insert into student_courses (student_curriculum_id, course_in_curriculum_id) values
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C001' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C002' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C003' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C004' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C005' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C006' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C007' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C008' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C009' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C011' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C012' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C014' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C015' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C016' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C017' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C018' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C019' and cic.curriculum_id = (select id from curricula where version = '2018'))),
((select sc.id from students s join student_curricula sc on s.id = sc.student_id where s.code = '220034001'), (select cic.id from courses_in_curriculum cic join courses c on cic.course_id = c.id where c.code = 'C020' and cic.curriculum_id = (select id from curricula where version = '2018')));
