-- Initial SQL seed file
insert into campuses (name, city, address) values
('Udenar Sede Principal', 'Pasto', 'Cra 21 # 26-85'),

insert into schools (name, code, campus_id) values
('Facultad de Ingeniería', 'FACING', 1);

insert into programs (name, code, school_id) values
('Ingeniería de Sistemas', '34', 1);

INSERT INTO courses (code, name) VALUES
('C001', 'Programación I'),
('C002', 'Introducción A La Ingeniería De Sistemas'),
('C003', 'Teoría General De Sistemas'),
('C004', 'Matemáticas Generales'),
('C005', 'Lógica Matemática'),
('C006', 'Programación II'),
('C007', 'Metodología De La Investigación'),
('C008', 'Calculo Diferencial'),
('C009', 'Algebra Lineal'),
('C010', 'Ingeniería Económica'),
('C011', 'Programación III'),
('C012', 'Ingeniería De Software I'),
('C013', 'Calculo Integral'),
('C014', 'Física I'),
('C015', 'Probabilidad Y Estadística'),
('C016', 'Estructuras De Datos'),
('C017', 'Ingeniería De Software II'),
('C018', 'Sistemas De Base De Datos'),
('C019', 'Cálculo De Varias Variables'),
('C020', 'Física II'),
('C021', 'Administración De Sistemas De Base De Datos'),
('C022', 'Ingeniería De Software III'),
('C023', 'Investigación De Operaciones'),
('C024', 'Ecuaciones Diferenciales'),
('C025', 'Administración De Empresas'),
('C026', 'Métodos Numéricos'),
('C027', 'Auditoria Y Seguridad Informática'),
('C028', 'Computación Gráfica'),
('C029', 'Circuitos Electrónicos'),
('C030', 'Sistemas Operativos'),
('C031', 'Sistemas Inteligentes'),
('C032', 'Lenguajes Formales Y Autómatas'),
('C033', 'Modelamiento Y Simulación'),
('C034', 'Redes De Computadores'),
('C035', 'Arquitectura De Computadores'),
('C036', 'Sistemas Basados En Conocimiento'),
('C037', 'Sistemas Y Servicios Telemáticos'),
('C038', 'Formulación Y Evaluación De Proyectos'),
('C039', 'Electiva'),
('C040', 'Electiva'),
('C041', 'Modelos De Computación'),
('C042', 'Emprendimiento'),
('C043', 'Proyecto De Investigación I'),
('C044', 'Electiva'),
('C045', 'Electiva'),
('C046', 'Ingeniería Legal'),
('C047', 'Proyecto De Investigación II'),
('C048', 'Electiva'),
('C049', 'Electiva'),
('C050', 'Formación en humanismo'),
('C051', 'Formación en cultura artística y fisica'),
('C052', 'Formación ciudadana'),
('C053', 'Formación en problemáticas de contexto'),
('C054', 'Lectura y producción de textos I'),
('C055', 'Lectura y producción de textos 2');


insert into curricula (version, created_at, program_id) values
('2018', '2017-12-01', 1);

insert into courses_in_curriculum (semester, credits, calendar, curriculum_id, course_id, prerequisite_id) values
(1, 4, 'A', 1, (select id from courses where code = 'C001'), null),
(1, 3, 'A', 1, (select id from courses where code = 'C002'), null),
(1, 3, 'A', 1, (select id from courses where code = 'C003'), null),
(1, 3, null, 1, (select id from courses where code = 'C004'), null),
(1, 3, null, 1, (select id from courses where code = 'C005'), null),
(2, 4, 'B', 1, (select id from courses where code = 'C006'), (select id from courses where code = 'C001')),
(2, 3, 'B', 1, (select id from courses where code = 'C007'), (select id from courses where code = 'C001')),
(2, 3, null, 1, (select id from courses where code = 'C008'), (select id from courses where code = 'C004')),
(2, 3, null, 1, (select id from courses where code = 'C009'), (select id from courses where code = 'C005')),
(2, 3, 'B', 1, (select id from courses where code = 'C010'), (select id from courses where code = 'C005')),
(3, 4, 'A', 1, (select id from courses where code = 'C011'), (select id from courses where code = 'C006')),
(3, 3, 'A', 1, (select id from courses where code = 'C012'), (select id from courses where code = 'C006')),
(3, 3, null, 1, (select id from courses where code = 'C013'), (select id from courses where code = 'C008')),
(3, 4, null, 1, (select id from courses where code = 'C014'), (select id from courses where code = 'C008')),
(3, 3, null, 1, (select id from courses where code = 'C015'), (select id from courses where code = 'C009')),
(4, 4, 'B', 1, (select id from courses where code = 'C016'), (select id from courses where code = 'C011')),
(4, 3, 'B', 1, (select id from courses where code = 'C017'), (select id from courses where code = 'C012')),
(4, 4, 'B', 1, (select id from courses where code = 'C018'), null),
(4, 3, null, 1, (select id from courses where code = 'C019'), (select id from courses where code = 'C013')),
(4, 4, null, 1, (select id from courses where code = 'C020'), (select id from courses where code = 'C014')),
(5, 3, 'A', 1, (select id from courses where code = 'C021'), (select id from courses where code = 'C018')),
(5, 3, 'A', 1, (select id from courses where code = 'C022'), (select id from courses where code = 'C017')),
(5, 3, 'A', 1, (select id from courses where code = 'C023'), (select id from courses where code = 'C009')),
(5, 3, null, 1, (select id from courses where code = 'C024'), (select id from courses where code = 'C019')),
(5, 3, 'A', 1, (select id from courses where code = 'C025'), (select id from courses where code = 'C010')),
(6, 3, 'B', 1, (select id from courses where code = 'C026'), (select id from courses where code = 'C008')),
(6, 3, 'B', 1, (select id from courses where code = 'C027'), null),
(6, 3, 'B', 1, (select id from courses where code = 'C028'), null),
(6, 3, 'B', 1, (select id from courses where code = 'C029'), (select id from courses where code = 'C020')),
(6, 4, 'B', 1, (select id from courses where code = 'C030'), null),
(7, 3, 'A', 1, (select id from courses where code = 'C031'), null),
(7, 3, 'A', 1, (select id from courses where code = 'C032'), null),
(7, 4, 'A', 1, (select id from courses where code = 'C033'), (select id from courses where code = 'C015')),
(7, 3, 'A', 1, (select id from courses where code = 'C034'), (select id from courses where code = 'C030')),
(7, 4, 'A', 1, (select id from courses where code = 'C035'), (select id from courses where code = 'C029')),
(8, 3, 'B', 1, (select id from courses where code = 'C036'), (select id from courses where code = 'C031')),
(8, 3, 'B', 1, (select id from courses where code = 'C037'), (select id from courses where code = 'C034')),
(8, 3, 'B', 1, (select id from courses where code = 'C038'), (select id from courses where code = 'C025')),
(8, 3, null, 1, (select id from courses where code = 'C039'), null),
(8, 3, null, 1, (select id from courses where code = 'C040'), null),
(9, 3, 'A', 1, (select id from courses where code = 'C041'), (select id from courses where code = 'C037')),
(9, 3, 'A', 1, (select id from courses where code = 'C042'), null),
(9, 3, 'A', 1, (select id from courses where code = 'C043'), null),
(9, 3, null, 1, (select id from courses where code = 'C044'), null),
(9, 3, null, 1, (select id from courses where code = 'C045'), null),
(10, 3, 'B', 1, (select id from courses where code = 'C046'), null),
(10, 3, 'B', 1, (select id from courses where code = 'C047'), (select id from courses where code = 'C043')),
(10, 3, null, 1, (select id from courses where code = 'C048'), null),
(10, 3, null, 1, (select id from courses where code = 'C049'), null),
(0, 2, null, 1, (select id from courses where code = 'C050'), null),
(0, 2, null, 1, (select id from courses where code = 'C051'), null),
(0, 2, null, 1, (select id from courses where code = 'C052'), null),
(0, 2, null, 1, (select id from courses where code = 'C053'), null),
(0, 1, null, 1, (select id from courses where code = 'C054'), null),
(0, 1, null, 1, (select id from courses where code = 'C055'), (select id from courses where code = 'C054'));